# Configuration file for Phenology Optimizer

# Data paths
model_config_fpath: /env_config/config.yaml
# If true, use working directory. Otherwise, use path in config.yaml
reset_base_fpath: True
cultivar: Chardonnay

# Optimizer configuration
init_points: 5
n_iter: 5
acq: EI
multithread: False
# Exploration parameter for UCB
kappa: 2.576
# Exploration parameter for expected improvement
xi: 0.01
loss_func: SUM_SLICE # SUM or SUM_SLICE
num_runs: 5

