# Configuration file for Phenology Optimizer

# Data paths
model_config_fpath: /env_config/config.yaml
# If true, use working directory. Otherwise, use path in config.yaml
reset_base_fpath: True
cultivar: Aligote

# Optimizer configuration
init_points: 50
n_iter: 20
alpha: 1e-10
acq: UCB
multithread: False
# Exploration parameter for UCB
kappa: 2.576
# Exploration parameter for expected improvement
xi: 0.01
loss_func: SUM_SLICE # SUM or SUM_SLICE
num_runs: 5

# Kernel parameters
kernel: RBF  # Matern, RBF
nu: 2.5


