# Configuration file for Phenology Optimizer

# Data paths
model_config_fpath: "/Users/wsolow/Projects/digital_twin/env_config/config.yaml"
cultivar: "Aligote"

# Optimizer configuration
init_points: 30
n_iter: 20
acq: EI

